[tools]
go = "latest"
python = "latest"
uv = "latest"
jj = "latest"
jjui = "latest"
hugo = "latest"
zellij = "latest"
usage = "latest"
node = "latest"
#ruby = "latest"
neovim = "latest"
opencode = "latest"
delta = "latest"
bat = "latest"
zoxide = "latest"
fzf = "latest"
eza = "latest"
rg = "latest"
fd = "latest"
sd = "latest"
jq = "latest"
jqp = "latest"
yq = "latest"
cue = "latest"
lua = "latest"
lazygit = "latest"
grex = "latest"
vale = "latest"
odin = "latest"
hledger = "latest"
hledger-flow = "latest"
1password-cli = "latest"
gh = "latest"

[settings]
python.uv_venv_auto = true
idiomatic_version_file_enable_tools = []
experimental = true




